we1s-web/app/create/views.py
import os
import shutil

from flask import abort, Blueprint, render_template, request

from app import db, app

create = Blueprint('create', __name__,
                   template_folder='templates')


def trim_json(json):
    for key, value in json.iteritems():
        if isinstance(value, dict):
            json[key] = trim_json(value)
        elif isinstance(value, list):
            for i in range(len(value)):
                value[i] = trim_json(value[i])
            json[key] = value
        elif isinstance(value, str):
            json[key] = value.strip(' \t')
    return json


def save_files(json):
    return json


def clean_up_fs(json):
    # In case that files were uploaded in different transactions, i.e editing a collection
    # delete all possible directories
    for uploaded_file in json['files']:
        path = os.path.join(app.config['UPLOAD_FOLDER'], uploaded_file['transactionId'])
        if os.path.exists(path):
            shutil.rmtree(path)


def write_to_db(json, collection):
    json = trim_json(json)
    if 'files' in json:
        json = save_files(json)
        clean_up_fs(json)
    json['path'] = json['path'].replace('/', ',')
    db[collection].update_one({'_id': json['_id']}, {'$set': json}, upsert=True)


@create.route('/create/corpus')
def create_corpus():
    return render_template('create/corpus.html')


@create.route('/create/publication', methods=['GET', 'POST'])
def create_publication():
    if request.method == 'POST':
        try:
            write_to_db(request.get_json(), 'Publications')
            return 'OK', 200
        except Exception as e:
            print e
            abort(500)
    return render_template('create/main.html',
                           formname='Publications Manifest Form',
                           formfile='create/publication.html',
                           use_date=True,
                           use_files=False)


@create.route('/create/collection', methods=['GET', 'POST'])
def create_collection():
    if request.method == 'POST':
        try:
            write_to_db(request.get_json(), 'Corpus')
            return 'OK', 200
        except Exception:
            abort(500)
    return render_template('create/main.html',
                           formname='Collection Manifest Form',
                           formfile='create/collection.html',
                           use_date=True,
                           use_files=False)


@create.route('/create/rawdata', methods=['GET', 'POST'])
def create_raw_data():
    if request.method == 'POST':
        try:
            write_to_db(request.get_json(), 'Corpus')
            return 'OK', 200
        except Exception:
            abort(500)
    return render_template('create/main.html',
                           formname='Raw Data Manifest Form',
                           formfile='create/rawdata.html',
                           use_date=False,
                           use_files=True)


@create.route('/create/processeddata', methods=['GET', 'POST'])
def create_processed_data():
    if request.method == 'POST':
        try:
            write_to_db(request.get_json(), 'Corpus')
            return 'OK', 200
        except Exception:
            abort(500)
    return render_template('create/main.html',
                           formname='Processed Data Manifest Form',
                           formfile='create/processeddata.html',
                           use_date=False,
                           use_files=True)


@create.route('/create/outputs', methods=['GET', 'POST'])
def create_outputs():
    if request.method == 'POST':
        try:
            write_to_db(request.get_json(), 'Corpus')
            return 'OK', 200
        except Exception:
            abort(500)
    return render_template('create/main.html',
                           formname='Outputs Manifest Form',
                           formfile='create/outputs.html',
                           use_date=False,
                           use_files=True)


@create.route('/create/related', methods=['GET', 'POST'])
def create_related():
    if request.method == 'POST':
        try:
            write_to_db(request.get_json(), 'Corpus')
            return 'OK', 200
        except Exception:
            abort(500)
    return render_template('create/main.html',
                           formname='Related Manifest Form',
                           formfile='create/related.html',
                           use_date=False,
                           use_files=True)


@create.route('/create/metadata', methods=['GET', 'POST'])
def create_metadata():
    if request.method == 'POST':
        try:
            write_to_db(request.get_json(), 'Corpus')
            return 'OK', 200
        except Exception:
            abort(500)
    return render_template('create/main.html',
                           formname='Metadata Manifest Form',
                           formfile='create/metadata.html',
                           use_date=False,
                           use_files=False)

we1s-web/app/templates/create/baseform.html
<script type="text/javascript">
    function resetForm() {
        $('#form').find('form')[0].reset();
    }
    function toHTML(json) {
        var html = '<ul>';
        for (var property in json) {
            if (json.hasOwnProperty(property)) {
                if (json[property] instanceof Array) {
                    html += '<li><b>' + property + '</b>:<ul>';
                    for (var i = 0; i < json[property].length; i++) {
                        html += '<li>' + toHTML(json[property][i]) + '</li>';
                    }
                    html += '</ul></li>';
                }
                else if (typeof(json[property]) == 'object') {
                    html += '<li><b>' + property + '</b>:' + toHTML(json[property]) + '</li>';
                }
                else if (typeof(json[property]) == 'string') {
                    html += '<li><b>' + property + '</b>: ' + json[property].toString().trim() + '</li>';
                }
            }
        }
        return html + '</ul>';
    }
    $(document).ready(function () {
        {% block defaultData %}
            var defaultData = null;
        {% endblock %}

        var transactionId = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {var r = Math.random()*16|0,v=c=='x'?r:r&0x3|0x8;return v.toString(16);});

        $("#form").alpaca({
            "data": defaultData,
            "schema": {
                "title": "Manifest Form",
                "type": "object",
                "properties": {
                    "namespace": {
                        "enum": ["WE1Sv1.0"],
                        "label": "namespace",
                        "type": "string",
                        "required": true
                    },
                    "_id": {
                        "type": "string",
                        "title": "_id",
                        "required": true
                    },
                    "path": {
                        "type": "string",
                        "title": "Path",
                        "required": true
                    },
                    {% block schema %}{% endblock %}
                }
            },
            "options": {
                "hideInitValidationError": true,
                "form": {
                    "attributes": {
                        "action": document.URL,
                        "method": "post"
                    },
                    "buttons": {
                        "submit": {
                            "title": "Submit",
                            "click": function () {
                                // Somewhat elaborate procedure to turn the json into a string
                                var value = this.getValue();
                                if (value.files) {
                                    for (var i = 0; i < value.files.length; i++) {
                                        var file = value.files[i];
                                        delete file.deleteUrl;
                                        delete file.deleteType;
                                        delete file.size;
                                        file.transactionId = transactionId;
                                    }
                                }
                                // Submit data by Ajax
                                $.ajax({
                                    type: "POST",
                                    url: document.URL,
                                    data: JSON.stringify(value),
                                    contentType: 'application/json',
                                    dataType: 'text',
                                    beforeSend: function () {
                                        console.log(JSON.stringify(value, null, "\t"));
                                    },
                                    success: function (result) {
                                        console.log(result);
                                        var htmlResult = toHTML(value);
                                        $('.modal-body').html(htmlResult);
                                        $('#myModal').modal();
                                    },
                                    error: function (jqXHR, textStatus, errorThrown) {
                                        $('.modal-body').html('Error: Your action could not be completed.\n' + jqXHR.responseText);
                                        $('#myModal').modal();
                                        console.log("Error: " + errorThrown);
                                    }
                                });
                            }
                        }
                    }
                },
                // Field configuration arrray
                "fields": {
                    "namespace": {
                        "type": "select"
                    },
                    "_id": {
                        // Remove initial 'The', replace space with "_"; remove error styling
                        "onFieldKeyup": function (e) {
                            var v = this.getValue();
                            v = v.replace(/The /g, "");
                            v = v.toLowerCase();
                            v = v.replace(/\s+/g, "_");
                            $('input[name="_id"]').val(v);
                            var idDiv = $("div").find('[data-alpaca-field-name="_id"]');
                            idDiv.removeClass("alpaca-required has-error alpaca-invalid");
                        }
                    },
                    {% block options_fields %}{% endblock %}
                } // End fields
            },// End options
            {%  block postRender %}{% endblock %}
        });
    });
</script>

we1s-web/app/templates/create/collection.html
{% extends 'create/baseform.html' %}
{% import 'create/commonschemas.html' as schemas %}
{% import 'create/commonoptions.html' as options %}

{% block defaultData %}
    var today = moment().format('YYYY-MM-DD');
    var defaultData = {
        "description": "bortaS <b>bIr</b> jablu’DI’ reH QaQqu’ nay’!",
        "namespace": "WE1Sv1.0",
        "date": {
            "start": today,
            "end": today
        }
    };
{% endblock %}

{% block schema %}
    {{ schemas.description('true') }},
    {{ schemas.date() }},
    {{ schemas.title() }},
    {{ schemas.label() }},
    "workstation": {
        "type":"string",
        "title": "Workstation"
    },
    "publications": {
        "type":"array",
        "title":"Publications",
        "required": true
    },
    "collectors": {
        "type":"array",
        "title":"Collectors",
        // Add "Collector Name" legend to subfields
        "items": {
            "title": "Collector Name",
            "type": "string"
        }
    },
    "queryTerms": {
        "type":"array",
        "title":"Query Terms"
    },
    "processes": {
        "type":"array",
        "title":"Processes"
    },
    {{ schemas.notes() }}
{% endblock %}

{% block options_fields %}
    "publications": {
        // On change, remove initial "The", replace whitespace with "_", send value to _id,
        // remove error styling
        "events": {
            "change": function () {
{#                var p = $('input[name="publications"]').val();#}
{#                p = p.replace(/The /g, "");#}
{#                p = p.toLowerCase();#}
{#                p = p.replace(/\s+/g, "_");#}
{#                $('input[name="_id"]').val(p);#}
{#                var idDiv = $("div").find('[data-alpaca-field-name="_id"]');#}
{#                idDiv.removeClass("alpaca-required has-error alpaca-invalid");#}
            }
        }
    },
    "collectors": {
        // Change add button text to "Add Author"
        "toolbar": {
            "showLabels": true,
            "actions": [
                {"label": "Add Collector", "action": "add" }]
        }
    },
    {{ options.path("/Corpus/") }},
    {{ options.description() }},
    {{ options.date() }},
    {{ options.notes() }}
{% endblock %}

{% block postRender %}
    "postRender": function (control) {
        // Hack to prepend the Publications label with a required star
        var pubsDiv = $("div").find('[data-alpaca-field-name="publications"]');
        var label = pubsDiv.children().first();
        $('<span class="alpaca-icon-required glyphicon glyphicon-star"></span>').prependTo(label);

        var start = control.childrenByPropertyId["date"].childrenByPropertyId["start"];
        var end = control.childrenByPropertyId["date"].childrenByPropertyId["end"];
        end.subscribe(start, function (val) {
            var endDate = new Date($('input[name="date_end"]').val());
            var startDate = new Date(val);
            if (endDate < startDate) {
                end.setValue(val);
            }
        });
    }
{% endblock %}

we1s-web/app/templates/create/corpus.html
{% extends "layout.html" %}


{% block styles %}
    <style type="text/css">
        .padded-row {
            padding: 5px;
            margin: 5px;
        }
    </style>
{% endblock %}


{% block content %}
    <div class="jumbotron" style="padding: 10px;">
    <div class="row padded-row">
    <div class="col-md-12">
        <h2>WhatEvery1Says Corpus Manifest Forms</h2>
        <br>
        <p style="text-align:center;">Select the type of manifest you would like to create. <a id="help" href="#"><span
                style="font-size:larger;" class="glyphicon glyphicon-question-sign" aria-hidden="true"
                aria-label="Help"></span></a></p>
    </div>

    <div class="row padded-row">
        <div class="col-md-4">
            <a class="btn btn-primary btn-lg btn-block" role="button"
               href="{{ url_for('create.create_collection') }}">Collection</a>
        </div>
        <div class="col-md-4">
            <a class="btn btn-primary btn-lg btn-block" role="button"
               href="{{ url_for('create.create_raw_data') }}">Raw Data</a>
        </div>
        <div class="col-md-4">
            <a class="btn btn-primary btn-lg btn-block" role="button"
               href="{{ url_for('create.create_processed_data') }}">Processed Data</a>
        </div>
    </div>

    <div class="row padded-row">
        <div class="col-md-4">
            <a class="btn btn-primary btn-lg btn-block" role="button"
               href="{{ url_for('create.create_metadata') }}">Metadata</a>
        </div>
        <div class="col-md-4">
            <a class="btn btn-primary btn-lg btn-block" role="button"
               href="{{ url_for('create.create_outputs') }}">Outputs</a>
        </div>
        <div class="col-md-4">
            <a class="btn btn-primary btn-lg btn-block" role="button"
               href="{{ url_for('create.create_related') }}">Related</a>
        </div>
    </div>

    <div class="row padded-row">
        <div class="col-md-4">
            <a class="btn btn-primary btn-lg btn-block" role="button" href="#"
               onclick="alert('This option is not yet available.');">Generic</a>
        </div>
    </div>

    <!-- Modal Containing Response to Database Query -->
    <div id="myModal" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog"
         aria-labelledby="myLargeModalLabel">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span></button>
                    <h3 class="modal-title" id="myModalLabel">Data Saved to MongoDB</h3>
                </div>
                <div class="modal-body" style="margin-top:10px;">
                    {{ msg }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block scripts %}
    <script>
        $(document).ready(function () {
            $("#help").click(function () {
                html = '<p>The corpus contains collections of manifests and files organized in a hierarchical structure. This page allows you to create manifests at each level of the hierarchy. Information about each type of manifest can be found in the draft schema, and, for convenience, links to the relevant portions of that document are provided here:</p><ul><li><a href="https://github.com/scottkleinman/WE1S/blob/master/DraftSchema.md#collections" target="_blank">Collections</a></li><li><a href="https://github.com/scottkleinman/WE1S/blob/master/DraftSchema.md#rawdata" target="_blank">Raw Data</a></li><li><a href="https://github.com/scottkleinman/WE1S/blob/master/DraftSchema.md#processeddata" target="_blank">Processed Data</a></li><li><a href="https://github.com/scottkleinman/WE1S/blob/master/DraftSchema.md#metadata" target="_blank">Metadata</a></li><li><a href="https://github.com/scottkleinman/WE1S/blob/master/DraftSchema.md#outputs" target="_blank">Outputs</a></li><li><a href="https://github.com/scottkleinman/WE1S/blob/master/DraftSchema.md#related" target="_blank">Related</a></li></ul><p>A typical path might be something like <code>Corpus/COLLECTION_NAME/RawData/</code>. In this example, the <code>RawData</code> path might be sub-divided by year, with each branch in the path containing files for a specific year. Since the basis for such branching can be anything, the schema provides a generic manifest node type which can be used to create a branching anywhere along the path.';
                $('#myModal .modal-title').html("<h3>Collection Help</h3>");
                $('#myModal .modal-body').html(html);
                $('#myModal').modal();
            });
        });
    </script>
{% endblock %}

we1s-web/app/templates/create/form.html
{% extends "layout.html" %}


{% block styles %}
    {{ super() }}
    <link type="text/css" rel="stylesheet"
          href={{ url_for('static', filename='lib/alpaca.min.css') }}/>
    <link type="text/css" rel="stylesheet" media="screen"
          href={{ url_for('static', filename='lib/bootstrap-datetimepicker.css') }}/>
{% endblock %}


{% block content %}
    <div class="jumbotron"><h2>WhatEvery1Says {{ formname }}</h2>
        <div id="form"></div>
    </div>
    <!-- Modal Containing Response to Database Query -->
    <div id="myModal" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog"
         aria-labelledby="myLargeModalLabel">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span></button>
                    <h3 class="modal-title" id="myModalLabel">Data Saved to MongoDB</h3>
                </div>
                <div class="modal-body" style="margin-top:10px;">
                    {{ msg }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block scripts %}
    {{ super() }}
    <script type="text/javascript"
            src="//cdn.ckeditor.com/4.5.10/full/ckeditor.js"></script>
    <script type="text/javascript"
            src={{ url_for('static', filename='lib/handlebars.min.js') }}></script>
    <script type="text/javascript"
            src={{ url_for('static', filename='lib/alpaca.min.js') }}></script>
    <script type="text/javascript"
            src={{ url_for('static', filename='lib/moment-with-locales.min.js') }}></script>
    <script type="text/javascript"
            src={{ url_for('static', filename='lib/bootstrap-datetimepicker.min.js') }}></script>
    <script type="text/javascript"
            src="{{ url_for('static', filename='scripts/' + formfile) }}"></script>
{% endblock %}

we1s-web/app/templates/create/main.html
{% extends "layout.html" %}


{% block styles %}
    <link type="text/css" rel="stylesheet"
          href={{ url_for('static', filename='lib/alpaca.min.css') }}/>
    {% if use_date %}
        <link type="text/css" rel="stylesheet" media="screen"
              href={{ url_for('static', filename='lib/bootstrap-datetimepicker.min.css') }}/>
    {% endif %}
    {% if use_files %}
        <link type="text/css" rel="stylesheet"
              href="{{ url_for('static', filename='lib/jquery_file_upload/css/jquery.fileupload.css') }}"/>
        <link type="text/css" rel="stylesheet"
              href="{{ url_for('static', filename='lib/jquery_file_upload/css/jquery.fileupload-ui.css') }}"/>
    {% endif %}
{% endblock %}


{% block content %}
    <div class="jumbotron"><h2>WhatEvery1Says {{ formname }}</h2>
        <p>
            <a class="btn btn-primary btn-lg" role="button" onclick="resetForm()">Reset Form</a>
        </p>
        <div id="form"></div>
    </div>
    <!-- Modal Containing Response to Database Query -->
    <div id="myModal" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog"
         aria-labelledby="myLargeModalLabel">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span></button>
                    <h3 class="modal-title" id="myModalLabel">Data Saved to MongoDB</h3>
                </div>
                <div class="modal-body" style="margin-top:10px;">
                    {{ msg }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block scripts %}
    {% if use_date %}
        <script type="text/javascript"
                src={{ url_for('static', filename='lib/moment-with-locales.min.js') }}></script>
        <script type="text/javascript"
                src={{ url_for('static', filename='lib/bootstrap-datetimepicker.min.js') }}></script>
    {% endif %}
    {% if use_files %}
        <script type="text/javascript"
                src="{{ url_for('static', filename='lib/jquery_file_upload/js/vendor/jquery.ui.widget.js') }}"></script>
        <script type="text/javascript"
                src="{{ url_for('static', filename='lib/jquery_file_upload/js/jquery.iframe-transport.js') }}"></script>
        <script type="text/javascript"
                src="{{ url_for('static', filename='lib/jquery_file_upload/js/jquery.fileupload.js') }}"></script>
        <script type="text/javascript"
                src="{{ url_for('static', filename='lib/jquery_file_upload/js/jquery.fileupload-process.js') }}"></script>
        <script type="text/javascript"
                src="{{ url_for('static', filename='lib/jquery_file_upload/js/jquery.fileupload-ui.js') }}"></script>
    {% endif %}
    <script type="text/javascript"
            src="//cdn.ckeditor.com/4.5.10/full/ckeditor.js"></script>
    <script type="text/javascript"
            src={{ url_for('static', filename='lib/handlebars.min.js') }}></script>
    <script type="text/javascript"
            src={{ url_for('static', filename='lib/alpaca.min.js') }}></script>
    {% include formfile %}
{% endblock %}

we1s-web/app/templates/create/metadata.html
{% extends 'create/baseform.html' %}
{% import 'create/commonschemas.html' as schemas %}
{% import 'create/commonoptions.html' as options %}

{% block defaultData %}
    var defaultData = {
        "_id": "Metadata",
        "description": "bortaS <b>bIr</b> jablu’DI’ reH QaQqu’ nay’!",
        "namespace": "WE1Sv1.0"
    };
{% endblock %}

{% block schema %}
    {{ schemas.description('false') }},
    {{ schemas.title() }},
    {{ schemas.label() }},
    {{ schemas.mimetype() }},
    {{ schemas.notes() }}
{% endblock %}

{% block options_fields %}
    {{ options.mimetype() }},
    {{ options.path("/Corpus/") }},
    {{ options.description() }},
    {{ options.date() }},
    {{ options.notes() }}
{% endblock %}

{% block postRender %}

{% endblock %}

we1s-web/app/templates/create/outputs.html
{% extends 'create/baseform.html' %}
{% import 'create/commonschemas.html' as schemas %}
{% import 'create/commonoptions.html' as options %}

{% block defaultData %}
    var defaultData = {
        "_id": "Outputs",
        "description": "bortaS <b>bIr</b> jablu’DI’ reH QaQqu’ nay’!",
        "namespace": "WE1Sv1.0"
    };
{% endblock %}

{% block schema %}
    {{ schemas.description('false') }},
    {{ schemas.title() }},
    {{ schemas.label() }},
    {{ schemas.mimetype() }},
    {{ schemas.notes() }}
{% endblock %}

{% block options_fields %}
    {{ options.mimetype() }},
    {{ options.path("/Corpus/") }},
    {{ options.description() }},
    {{ options.date() }},
    {{ options.notes() }}
{% endblock %}

{% block postRender %}

{% endblock %}

we1s-web/app/templates/create/processeddata.html
{% extends 'create/baseform.html' %}
{% import 'create/commonschemas.html' as schemas %}
{% import 'create/commonoptions.html' as options %}

{% block defaultData %}
    var defaultData = {
        "_id": "Metadata",
        "description": "bortaS <b>bIr</b> jablu’DI’ reH QaQqu’ nay’!",
        "namespace": "WE1Sv1.0"
    };
{% endblock %}

{% block schema %}
    {{ schemas.description('false') }},
    {{ schemas.title() }},
    {{ schemas.label() }},
    "processes": {
        "type":"array",
        "title":"Processes"
    },
    {{ schemas.notes() }}
{% endblock %}

{% block options_fields %}
    {{ options.path("/Corpus/") }},
    "processes": {
        // Make sure the path begins with /Corpus/ and ends with /;
        // Change , to /. The change code below is ugly, but it works.
        "events": {
            "change": function(e) {
                // Each process is recorded as processes_0, processes_1, etc.
                $("input[name^='processes_']").each(function(index, value) {
                    var process_num = $(this).attr("name");
                    var item = value.value;
                    if (item.substring(0,8) != "/Corpus/") {
                      item = "/Corpus/" + item + "/";
                      item = item.replace(/\/\/+/g, '/');
                      item = item.replace(/,/g, "/");
                      $("input[name='" +process_num+ "']").val(item);
                    }
                    if (item.substring(-1) != "/") {
                      item = item + "/";
                      item = item.replace(/\/\/+/g, '/');
                      $("input[name='" +process_num+ "']").val(item);
                    }
                });
            }
        },
        // Change add button text to "Add Process"
        "toolbar": {
            "showLabels": true,
            "actions": [
                {"label": "Add Process", "action": "add"}
            ]
        }
    },
    {{ options.description() }},
    {{ options.date() }},
    {{ options.notes() }}
{% endblock %}

{% block postRender %}

{% endblock %}

we1s-web/app/templates/create/rawdata.html
{% extends 'create/baseform.html' %}
{% import 'create/commonschemas.html' as schemas %}
{% import 'create/commonoptions.html' as options %}

{% block defaultData %}
    var defaultData = {
        "_id": "RawData",
        "description": "bortaS <b>bIr</b> jablu’DI’ reH QaQqu’ nay’!",
        "namespace": "WE1Sv1.0"
    };
{% endblock %}

{% block schema %}
    {{ schemas.description('false') }},
    {{ schemas.title() }},
    {{ schemas.label() }},
    "OCR": {
        "type":"boolean",
        "default": false
    },
    "rights": {
        "title": "Rights",
        "type":"string"
    },
    "relationships": {
        "title": "Relationships",
        "type": "array",
        "items": {
            "type": "object",
            "properties": {
                "rType": {
                    "default": "isPartOf",
                    "schema": {
                        "enum": ["isPartOf", "hasPart"],
                    }
                },
                "rValue": {
                    "title": "Relationship Value",
                    "type": "string"
                }
            }
        }
    },
    {{ schemas.notes() }},
    {{ schemas.files('false') }}
{% endblock %}

{% block options_fields %}
    "relationships": {
        "items": {
            "fields": {
                "rType": {
                    "type": "select",
                    "label": "Relationship Type",
                    "dataSource": ["isPartOf", "hasPart"],
                    "emptySelectFirst": true,
                    "removeDefaultNone": true,
                }
            }
        }
    },
    "OCR": {
        "type": "checkbox",
        "rightLabel": "OCR",
        "default": false
    },
    {{ options.path("/Corpus/") }},
    {{ options.description() }},
    {{ options.date() }},
    {{ options.notes() }},
    {{ options.files() }}
{% endblock %}

{% block postRender %}

{% endblock %}

we1s-web/app/templates/create/related.html
{% extends 'create/baseform.html' %}
{% import 'create/commonschemas.html' as schemas %}
{% import 'create/commonoptions.html' as options %}

{% block defaultData %}
    var defaultData = {
        "_id": "Related",
        "description": "bortaS <b>bIr</b> jablu’DI’ reH QaQqu’ nay’!",
        "namespace": "WE1Sv1.0"
    };
{% endblock %}

{% block schema %}
    {{ schemas.description('false') }},
    {{ schemas.title() }},
    {{ schemas.label() }},
    {{ schemas.mimetype() }},
    {{ schemas.notes() }}
{% endblock %}

{% block options_fields %}
    {{ options.mimetype() }},
    {{ options.path("/Corpus/") }},
    {{ options.description() }},
    {{ options.date() }},
    {{ options.notes() }}
{% endblock %}

{% block postRender %}

{% endblock %}