we1s-web/app/create/views.py
import os
import shutil

from flask import abort, Blueprint, render_template, request

from app import db, app

create = Blueprint('create', __name__,
                   template_folder='templates')


def trim_json(json):
    for key, value in json.iteritems():
        if isinstance(value, dict):
            json[key] = trim_json(value)
        elif isinstance(value, list):
            for i in range(len(value)):
                value[i] = trim_json(value[i])
            json[key] = value
        elif isinstance(value, str):
            json[key] = value.strip(' \t')
    return json


def save_files(json):
    return json


def clean_up_fs(json):
    # In case that files were uploaded in different transactions, i.e editing a collection
    # delete all possible directories
    for uploaded_file in json['files']:
        path = os.path.join(app.config['UPLOAD_FOLDER'], uploaded_file['transactionId'])
        if os.path.exists(path):
            shutil.rmtree(path)


def write_to_db(json, collection):
    json = trim_json(json)
    if 'files' in json:
        json = save_files(json)
        clean_up_fs(json)
    json['path'] = json['path'].replace('/', ',')
    db[collection].update_one({'_id': json['_id']}, {'$set': json}, upsert=True)


@create.route('/create/corpus')
def create_corpus():
    return render_template('create/corpus.html')


@create.route('/create/publication', methods=['GET', 'POST'])
def create_publication():
    if request.method == 'POST':
        try:
            write_to_db(request.get_json(), 'Publications')
            return 'OK', 200
        except Exception as e:
            print e
            abort(500)
    return render_template('create/main.html',
                           formname='Publications Manifest Form',
                           formfile='create/publication.html',
                           use_date=True,
                           use_files=False)


@create.route('/create/collection', methods=['GET', 'POST'])
def create_collection():
    if request.method == 'POST':
        try:
            write_to_db(request.get_json(), 'Corpus')
            return 'OK', 200
        except Exception:
            abort(500)
    return render_template('create/main.html',
                           formname='Collection Manifest Form',
                           formfile='create/collection.html',
                           use_date=True,
                           use_files=False)


@create.route('/create/rawdata', methods=['GET', 'POST'])
def create_raw_data():
    if request.method == 'POST':
        try:
            write_to_db(request.get_json(), 'Corpus')
            return 'OK', 200
        except Exception:
            abort(500)
    return render_template('create/main.html',
                           formname='Raw Data Manifest Form',
                           formfile='create/rawdata.html',
                           use_date=False,
                           use_files=True)


@create.route('/create/processeddata', methods=['GET', 'POST'])
def create_processed_data():
    if request.method == 'POST':
        try:
            write_to_db(request.get_json(), 'Corpus')
            return 'OK', 200
        except Exception:
            abort(500)
    return render_template('create/main.html',
                           formname='Processed Data Manifest Form',
                           formfile='create/processeddata.html',
                           use_date=False,
                           use_files=True)


@create.route('/create/outputs', methods=['GET', 'POST'])
def create_outputs():
    if request.method == 'POST':
        try:
            write_to_db(request.get_json(), 'Corpus')
            return 'OK', 200
        except Exception:
            abort(500)
    return render_template('create/main.html',
                           formname='Outputs Manifest Form',
                           formfile='create/outputs.html',
                           use_date=False,
                           use_files=True)


@create.route('/create/related', methods=['GET', 'POST'])
def create_related():
    if request.method == 'POST':
        try:
            write_to_db(request.get_json(), 'Corpus')
            return 'OK', 200
        except Exception:
            abort(500)
    return render_template('create/main.html',
                           formname='Related Manifest Form',
                           formfile='create/related.html',
                           use_date=False,
                           use_files=True)


@create.route('/create/metadata', methods=['GET', 'POST'])
def create_metadata():
    if request.method == 'POST':
        try:
            write_to_db(request.get_json(), 'Corpus')
            return 'OK', 200
        except Exception:
            abort(500)
    return render_template('create/main.html',
                           formname='Metadata Manifest Form',
                           formfile='create/metadata.html',
                           use_date=False,
                           use_files=False)

we1s-web/app/templates/index.html
{% extends "layout.html" %}

{% block content %}
    <div class="jumbotron">
        <h2>WhatEvery1Says Demo</h2>
        <p align="center">This is the demo website for managing WhatEvery1Says manifests.</p>
        <h3>To Do:</h3>
        <ol>
            <li>Authors and notes store sequence order implicitly as Javascript arrays (and Python lists in processing).
                In order to enable explicit storage of sequence order, they need to be converted to objects
                (dictionaries) for storage in the database and an option to save explicit sequencing needs to be added
                to the form.
            </li>
        </ol>
        <h3>To Do for Collections:</h3>
        <ol>
            <li>Although forms are available for each of the Collection node types link to forms, the forms may not
                accurately reflect the schema (they're mostly place-holders). Only the Collection type will save
                accurately to the database.
            </li>
            <li>The Record node type is for editing individual file manifests. It doesn't really make sense without an
                accompanying file upload function in the form.
            </li>
        </ol>
        <h3>Other:</h3>
        <ol>
            <li>There needs to be a bulk file upload function.</li>
        </ol>
    </div>
{% endblock %}

we1s-web/app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>WhatEvery1Says</title>
    <link rel="stylesheet" type="text/css"
          href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css"
          href="{{ url_for('static', filename='css/styles.css') }}"/>
    {% block styles %}{% endblock %}
    <script type="text/javascript"
            src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="{{ url_for('static', filename='lib/bootbox.min.js') }}"></script>
    {% block headscripts %}{% endblock %}
</head>

<body>

{% include "navbar.html" %}

<div class="container">
    {% block content %}{% endblock %}
</div>

<footer>
    © 2015
    <a href="http://4humanities.org/" target="_blank">4Humanities</a>
    <a href="http://4humanities.org/category/whatevery1says/" target="_blank">WhatEvery1Says Research Group</a>
    ·
    <br>
    This site is licensed under the <a href="http://opensource.org/licenses/MIT">MIT License</a>.
</footer>

<script type="text/javascript"
            src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
{% block scripts %}{% endblock %}

</body>
</html>

we1s-web/app/templates/navbar.html
{% block navbar %}
    <nav role="navigation" class="navbar navbar-fixed-top navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false"
                        aria-controls="navbar" class="navbar-toggle collapsed">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="#" class="navbar-brand">WE1S</a>
            </div>

            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/">Home</a></li>
                    <li class="dropdown">
                        <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="dropdown-toggle">
                            Display
                            <span class="caret"></span>
                        </a>
                        <ul role="menu" class="dropdown-menu">
                            <li><a href="{{ url_for("display_publications") }}">Publications</a></li>
                            <li><a href="{{ url_for("display_corpora") }}">Corpus</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="dropdown-toggle">
                            Create
                            <span class="caret"></span>
                        </a>
                        <ul role="menu" class="dropdown-menu">
                            <li><a href="{{ url_for("create.create_publication") }}">Publication Manifest</a></li>
                            <li><a href="{{ url_for("create.create_corpus") }}">Corpus Manifest</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Corpus Record</a></li>
                        </ul>
                    </li>
                </ul>
{#                <ul class="nav navbar-nav navbar-right">#}
{#                    <li><a id="searchHelp" href="#">#}
{#                        <span class="glyphicon glyphicon-question-sign" aria-hidden="true" aria-label="Help"></span>#}
{#                    </a></li>#}
{#                </ul>#}
{#                <form class="navbar-form navbar-right" role="search">#}
{#                    <div class="form-group">#}
{#                        <input id="search" type="text" class="form-control" placeholder="Search">#}
{#                    </div>#}
{#                    <button id="searchSubmit" class="btn btn-default">Submit</button>#}
{#                </form>#}
            </div>
        </div>
    </nav>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#searchHelp").click(function () {
                html = "<p>The search option will list all publications and collections containing the (case insensitive) search string in the <code>_id</code> property. Each listing links to the document's edit form.";
                $('#searchModal .modal-title').html("<h3>Search Help</h3>");
                $('#searchModal .modal-body').html(html);
                $('#searchModal').modal();
            });

            $("#searchSubmit").click(function (e) {
                e.preventDefault();
                var query = {"query": $("#search").val()};
                $.ajax({
                    type: "POST",
                    url: '',
                    data: JSON.stringify(query, null, '\t'),
                    contentType: 'application/json;charset=UTF-8',
                    headers: {'dummyFunction': 'dummy'},
                    beforeSend: function () {
                        //alert('Sending...');
                    },
                    success: function (htmlResult) {
                        $('.modal-body').html(htmlResult);
                        $('#searchModal').modal();
                    },
                    complete: function () {
                        //alert('Database action complete.');
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        $('.modal-body').html('Error: Your action could not be completed.');
                        $('#myModal').modal();
                        console.log("Error: " + errorThrown);
                    }
                });
            });
        });
    </script>

    <!-- Modal Containing Response to Database Query -->
    <div id="searchModal" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog"
         aria-labelledby="myLargeModalLabel">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h3 class="modal-title" id="myModalLabel">Search Results</h3>
                </div>
                <div class="modal-body" style="margin-top:10px;">
                    {{ msg }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}